In [37]:
import pandas as pd

In [82]:
df01=pd.read_csv("union.csv")

In [83]:
df01

,Table Names,Outgoing,month and year of doc date,DOC_NUM,DOC_ITEM,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,...,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,CPQUAOU,PO_UNIT,DENOMINTR,NUMERATOR,BASE_UOM,DB_CRD_IND
0,10.2.3.222..224/PFPUED01,3808.0,11/1/2019,4502565556,1,5,11/12/2019,F,W022,92055938,...,WND1,X,L,0022,3808.0,ST,1,1,ST,X
1,10.2.3.222..224/PFPUED01,634.0,11/1/2019,4502565620,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,634.0,ST,1,1,ST,X
2,10.2.3.222..224/PFPUED01,124.0,11/1/2019,4502565632,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,124.0,ST,1,1,ST,X
3,10.2.3.222..224/PFPUED01,960.0,11/1/2019,4502567441,1,5,11/14/2019,F,W022,92054591,...,WND1,X,L,0022,960.0,M,1,1,M,X
4,10.2.3.222..224/PFPUED01,920.0,11/1/2019,4502567444,1,5,11/14/2019,F,W022,92055931,...,WND1,X,L,0022,920.0,M,1,1,M,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,10.2.3.222..224/PFPUED01-1,100000.0,8/1/2020,4502720545,1,5,8/3/2020,F,W022,92065741,...,DE02,X,NaN,DE01,100000.0,ST,1,1,ST,X
409,10.2.3.222..224/PFPUED01-1,97000.0,8/1/2020,4502720661,2,5,8/3/2020,F,W022,92061972,...,DE02,X,NaN,DE01,97000.0,ST,1,1,ST,X
410,10.2.3.222..224/PFPUED01-1,144000.0,8/1/2020,4502720661,1,5,8/3/2020,F,W022,92061972,...,DE02,X,NaN,DE01,144000.0,ST,1,1,ST,X
411,10.2.3.222..224/PFPUED01-1,2900.0,8/1/2020,4502720674,1,5,8/3/2020,F,W022,92052041,...,DE02,X,NaN,DE01,2900.0,ST,1,1,ST,X
412,10.2.3.222..224/PFPUED01-1,200.0,9/1/2020,4502747405,1,7,9/24/2020,F,W022,92054591,...,DE02,X,NaN,DE01,200.0,M,1,1,M,X

In [5]:
df15=pd.read_csv("PFPUED15_without plant code.csv")

MemoryError: Unable to allocate 1.10 GiB for an array with shape (8, 18483734) and data type object

In [84]:
list(df01.columns)

['Table Names',
 'Outgoing',
 'month and year of doc date',
 'DOC_NUM',
 'DOC_ITEM',
 'PROCESSKEY',
 'DOC_DATE',
 'DOC_CAT',
 'PURCH_ORG',
 'VENDOR',
 'BWAPPLNM',
 'FINAL_INV',
 'MATERIAL',
 'PLANT',
 'GR_RE_IND',
 'UCDELE_IND',
 'COMP_CODE',
 'CPQUAOU',
 'PO_UNIT',
 'DENOMINTR',
 'NUMERATOR',
 'BASE_UOM',
 'DB_CRD_IND']

In [43]:
df15=pd.read_csv("PFPUED15.csv")

In [44]:
list(df15.columns)

['Incoming',
 'month and year of psting date',
 'New GR QTY',
 'DOC_NUM',
 'DOC_ITEM',
 'MOVE_TYPE',
 'GR_QTY',
 'PLANT',
 'PSTNG_DATE',
 'DCINDIC',
 '/BIC/PURCH_ORG',
 'VENDOR',
 'MATERIAL']

In [45]:
dfreport=pd.read_csv("Reporting Date.csv")

In [46]:
dfreport.dtypes

Reporting Date    object
dtype: object

In [85]:
df01.dtypes

Table Names                    object
Outgoing                      float64
month and year of doc date     object
DOC_NUM                        object
DOC_ITEM                        int64
PROCESSKEY                      int64
DOC_DATE                       object
DOC_CAT                        object
PURCH_ORG                      object
VENDOR                          int64
BWAPPLNM                       object
FINAL_INV                      object
MATERIAL                       object
PLANT                          object
GR_RE_IND                      object
UCDELE_IND                     object
COMP_CODE                      object
CPQUAOU                       float64
PO_UNIT                        object
DENOMINTR                       int64
NUMERATOR                       int64
BASE_UOM                       object
DB_CRD_IND                     object
dtype: object

In [48]:
df15.dtypes

Incoming                         float64
month and year of psting date     object
New GR QTY                       float64
DOC_NUM                           object
DOC_ITEM                           int64
MOVE_TYPE                         object
GR_QTY                           float64
PLANT                             object
PSTNG_DATE                        object
DCINDIC                           object
/BIC/PURCH_ORG                    object
VENDOR                             int64
MATERIAL                          object
dtype: object

In [49]:
df01.head()

,Table Names,Outgoing,month and year of doc date,DOC_NUM,DOC_ITEM,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,...,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,CPQUAOU,PO_UNIT,DENOMINTR,NUMERATOR,BASE_UOM,DB_CRD_IND
0,10.2.3.222..224/PFPUED01,3808.0,11/1/2019,4502565556,1,5,11/12/2019,F,W022,92055938,...,WND1,X,L,0022,3808.0,ST,1,1,ST,X
1,10.2.3.222..224/PFPUED01,634.0,11/1/2019,4502565620,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,634.0,ST,1,1,ST,X
2,10.2.3.222..224/PFPUED01,124.0,11/1/2019,4502565632,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,124.0,ST,1,1,ST,X
3,10.2.3.222..224/PFPUED01,960.0,11/1/2019,4502567441,1,5,11/14/2019,F,W022,92054591,...,WND1,X,L,0022,960.0,M,1,1,M,X
4,10.2.3.222..224/PFPUED01,920.0,11/1/2019,4502567444,1,5,11/14/2019,F,W022,92055931,...,WND1,X,L,0022,920.0,M,1,1,M,X

In [50]:
df15.head()

,Incoming,month and year of psting date,New GR QTY,DOC_NUM,DOC_ITEM,MOVE_TYPE,GR_QTY,PLANT,PSTNG_DATE,DCINDIC,/BIC/PURCH_ORG,VENDOR,MATERIAL
0,9072.0,3/1/2014,9072.0,4501401456,9,101,9072.0,W110,3/31/2014,S,W022,91004118,7501821
1,1.0,3/1/2014,1.0,4501408806,10,101,1.0,W400,3/31/2014,S,W022,91011428,0054155
2,2592.0,3/1/2014,2592.0,4501401639,4,101,2592.0,W110,3/31/2014,S,W022,91004118,7510581
3,1000.0,3/1/2014,1000.0,4501413613,2,907,1000.0,W230,3/31/2014,S,W022,91005944,7680861
4,330.0,3/1/2014,330.0,4501427343,1,101,330.0,W210,3/31/2014,S,W022,91006208,0896031

In [51]:
dfreport.head()

  Reporting Date
0         Jan-15
1         Feb-15
2         Mar-15
3         Apr-15
4         May-15

In [52]:
import datetime

In [86]:
df01["month and year of doc date"]=pd.to_datetime(df01["month and year of doc date"])

In [54]:
df15["month and year of psting date"]=pd.to_datetime(df15["month and year of psting date"])

In [55]:
dfreport["Reporting Date"]=pd.date_range(start='1/1/2015', end='12/31/2020',freq='MS')

In [56]:
dfreport["Reporting Date"]=pd.to_datetime(dfreport["Reporting Date"])

In [87]:
df01.dtypes

Table Names                           object
Outgoing                             float64
month and year of doc date    datetime64[ns]
DOC_NUM                               object
DOC_ITEM                               int64
PROCESSKEY                             int64
DOC_DATE                              object
DOC_CAT                               object
PURCH_ORG                             object
VENDOR                                 int64
BWAPPLNM                              object
FINAL_INV                             object
MATERIAL                              object
PLANT                                 object
GR_RE_IND                             object
UCDELE_IND                            object
COMP_CODE                             object
CPQUAOU                              float64
PO_UNIT                               object
DENOMINTR                              int64
NUMERATOR                              int64
BASE_UOM                              object
DB_CRD_IND                            object
dtype: object

In [58]:
df15.dtypes

Incoming                                float64
month and year of psting date    datetime64[ns]
New GR QTY                              float64
DOC_NUM                                  object
DOC_ITEM                                  int64
MOVE_TYPE                                object
GR_QTY                                  float64
PLANT                                    object
PSTNG_DATE                               object
DCINDIC                                  object
/BIC/PURCH_ORG                           object
VENDOR                                    int64
MATERIAL                                 object
dtype: object

In [88]:
df01=df01.rename(columns={"month and year of doc date":"Reporting Date"})

In [60]:
df01.head()

,Table Names,Outgoing,Reporting Date,DOC_NUM,DOC_ITEM,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,...,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,CPQUAOU,PO_UNIT,DENOMINTR,NUMERATOR,BASE_UOM,DB_CRD_IND
0,10.2.3.222..224/PFPUED01,3808.0,2019-11-01,4502565556,1,5,11/12/2019,F,W022,92055938,...,WND1,X,L,0022,3808.0,ST,1,1,ST,X
1,10.2.3.222..224/PFPUED01,634.0,2019-11-01,4502565620,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,634.0,ST,1,1,ST,X
2,10.2.3.222..224/PFPUED01,124.0,2019-11-01,4502565632,1,5,11/12/2019,F,W022,92052041,...,WND1,X,L,0022,124.0,ST,1,1,ST,X
3,10.2.3.222..224/PFPUED01,960.0,2019-11-01,4502567441,1,5,11/14/2019,F,W022,92054591,...,WND1,X,L,0022,960.0,M,1,1,M,X
4,10.2.3.222..224/PFPUED01,920.0,2019-11-01,4502567444,1,5,11/14/2019,F,W022,92055931,...,WND1,X,L,0022,920.0,M,1,1,M,X

In [61]:
df15=df15.rename(columns={"month and year of psting date":"Reporting Date"})

In [89]:
df01=df01.drop(columns=["DOC_NUM","DOC_ITEM","PROCESSKEY","DOC_DATE","DOC_CAT","CPQUAOU","PO_UNIT","DENOMINTR","NUMERATOR","BASE_UOM"])

In [90]:
df01=df01.drop(columns=["Table Names"])

In [91]:
df01

,Outgoing,Reporting Date,PURCH_ORG,VENDOR,BWAPPLNM,FINAL_INV,MATERIAL,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,DB_CRD_IND
0,3808.0,2019-11-01,W022,92055938,MM,NaN,0895971,WND1,X,L,0022,X
1,634.0,2019-11-01,W022,92052041,MM,X,7513191,WND1,X,L,0022,X
2,124.0,2019-11-01,W022,92052041,MM,X,7513581,WND1,X,L,0022,X
3,960.0,2019-11-01,W022,92054591,MM,X,7687861,WND1,X,L,0022,X
4,920.0,2019-11-01,W022,92055931,MM,NaN,7687421,WND1,X,L,0022,X
...,...,...,...,...,...,...,...,...,...,...,...,...
408,100000.0,2020-08-01,W022,92065741,MM,X,7509781,DE02,X,NaN,DE01,X
409,97000.0,2020-08-01,W022,92061972,MM,X,7509751,DE02,X,NaN,DE01,X
410,144000.0,2020-08-01,W022,92061972,MM,X,7509751,DE02,X,NaN,DE01,X
411,2900.0,2020-08-01,W022,92052041,MM,X,7513201,DE02,X,NaN,DE01,X
412,200.0,2020-09-01,W022,92054591,MM,X,7687821,DE02,X,NaN,DE01,X

In [65]:
df15=df15.drop(columns=["DOC_NUM","DOC_ITEM","PSTNG_DATE","GR_QTY"])

In [93]:
df15

,Incoming,Reporting Date,New GR QTY,MOVE_TYPE,PLANT,DCINDIC,/BIC/PURCH_ORG,VENDOR,MATERIAL
92,21450.0,2014-03-01,21450.0,101,W210,S,W022,91004612,0875162
94,1000.0,2014-03-01,1000.0,907,W230,S,W022,91005944,7680761
115,330.0,2019-10-01,330.0,101,WND1,S,W022,92055938,0896031
116,5616.0,2019-10-01,5616.0,101,WND1,S,W022,92055938,0897011
117,5616.0,2019-10-01,5616.0,101,WND1,S,W022,92055938,0895961
...,...,...,...,...,...,...,...,...,...
554745,7200.0,2017-02-01,7200.0,101,WND1,S,W022,91004573,7502451
554746,1600.0,2017-02-01,1600.0,101,WND1,S,W022,91004573,7502451
554747,11200.0,2017-02-01,11200.0,101,WND1,S,W022,91004573,7502451
554748,2400.0,2017-02-01,2400.0,101,WND1,S,W022,91004573,7502451
554749,1600.0,2017-02-01,1600.0,101,WND1,S,W022,91004573,7502451

In [94]:
df15.PLANT.unique()

array(['W210', 'W230', 'WND1', 'SGMQ', '3055', 'W400', 'W110', 'W120',
       'W220'], dtype=object)

In [80]:
df15_plant = df15.loc[(df15['PLANT'] == 'WND1') | (df15['PLANT'] == 'DE02')]
#display df15 which has wnd1 and de02 plant code

In [81]:
df15_plant.PLANT.unique()

array(['WND1'], dtype=object)

In [71]:
df01_rep=pd.merge(dfreport,df01,how="left",on="Reporting Date")

In [72]:
df01_rep

,Reporting Date,Table Names,Outgoing,DOC_NUM,DOC_ITEM,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,...,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,CPQUAOU,PO_UNIT,DENOMINTR,NUMERATOR,BASE_UOM,DB_CRD_IND
0,2015-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,2020-10-01,10.2.3.222..224/PFPUED01-1,9638.0,4502751824,2.0,5.0,10/1/2020,F,W022,92055213.0,...,DE02,X,NaN,DE01,9638.0,ST,1.0,1.0,ST,X
450,2020-11-01,10.2.3.222..224/PFPUED01-1,176000.0,4502770064,1.0,6.0,11/2/2020,F,W022,92058624.0,...,DE02,X,NaN,DE01,176000.0,ST,1.0,1.0,ST,X
451,2020-11-01,10.2.3.222..224/PFPUED01-1,24180.0,4502774218,1.0,5.0,11/9/2020,F,W022,92060258.0,...,DE02,X,NaN,DE01,24180.0,KG,1.0,1.0,KG,X
452,2020-11-01,10.2.3.222..224/PFPUED01-1,176000.0,4502770064,1.0,5.0,11/2/2020,F,W022,92058624.0,...,DE02,X,NaN,DE01,176000.0,ST,1.0,1.0,ST,X
453,2020-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
df01_rep.sort_values(by="Reporting Date").tail()

,Reporting Date,Table Names,Outgoing,DOC_NUM,DOC_ITEM,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,...,PLANT,GR_RE_IND,UCDELE_IND,COMP_CODE,CPQUAOU,PO_UNIT,DENOMINTR,NUMERATOR,BASE_UOM,DB_CRD_IND
442,2020-10-01,10.2.3.222..224/PFPUED01-1,9000.0,4502751764,3.0,5.0,10/1/2020,F,W022,92055213.0,...,DE02,X,NaN,DE01,9000.0,ST,1.0,1.0,ST,X
452,2020-11-01,10.2.3.222..224/PFPUED01-1,176000.0,4502770064,1.0,5.0,11/2/2020,F,W022,92058624.0,...,DE02,X,NaN,DE01,176000.0,ST,1.0,1.0,ST,X
450,2020-11-01,10.2.3.222..224/PFPUED01-1,176000.0,4502770064,1.0,6.0,11/2/2020,F,W022,92058624.0,...,DE02,X,NaN,DE01,176000.0,ST,1.0,1.0,ST,X
451,2020-11-01,10.2.3.222..224/PFPUED01-1,24180.0,4502774218,1.0,5.0,11/9/2020,F,W022,92060258.0,...,DE02,X,NaN,DE01,24180.0,KG,1.0,1.0,KG,X
453,2020-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
df15_rep=pd.merge(dfreport,df15,how="left",on="Reporting Date")

In [38]:
df15_rep

,Reporting Date,Incoming,New GR QTY,DOC_NUM,DOC_ITEM,MOVE_TYPE,GR_QTY,PLANT,PSTNG_DATE,DCINDIC,/BIC/PURCH_ORG,VENDOR,MATERIAL
0,2015-01-01,-2.0,-2.0,4501565850,1.0,102,2.0,W400,1/8/2015,H,W022,91000050.0,0062154
1,2015-01-01,-1512.0,-1512.0,4501549077,2.0,102,1512.0,W110,1/6/2015,H,W022,91004118.0,7560051
2,2015-01-01,-8.0,-8.0,4501565923,71.0,102,8.0,W400,1/19/2015,H,W022,91006186.0,0066009
3,2015-01-01,798.4,798.4,4501561724,1.0,101,798.4,W130,1/7/2015,S,W022,91004599.0,7507124
4,2015-01-01,898.2,898.2,4501561724,1.0,101,898.2,W130,1/7/2015,S,W022,91004599.0,7507124
...,...,...,...,...,...,...,...,...,...,...,...,...,...
371584,2020-11-01,0.0,-10000.0,4502776215,1.0,161,10000.0,DE02,11/16/2020,H,W022,92061972.0,7501801
371585,2020-11-01,50.0,50.0,4502776084,8.0,101,50.0,DE02,11/17/2020,S,W022,92068309.0,0063875
371586,2020-11-01,7922.0,7922.0,4502777993,1.0,101,7922.0,DES2,11/16/2020,S,W022,92055760.0,F00000384
371587,2020-11-01,1800.0,1800.0,4502777500,7.0,101,1800.0,DE02,11/16/2020,S,W022,92055938.0,0896481
371588,2020-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df15_rep=df15_rep.drop(columns=["PLANT"])

In [40]:
df15_rep

,Reporting Date,Incoming,New GR QTY,DOC_NUM,DOC_ITEM,MOVE_TYPE,GR_QTY,PSTNG_DATE,DCINDIC,/BIC/PURCH_ORG,VENDOR,MATERIAL
0,2015-01-01,-2.0,-2.0,4501565850,1.0,102,2.0,1/8/2015,H,W022,91000050.0,0062154
1,2015-01-01,-1512.0,-1512.0,4501549077,2.0,102,1512.0,1/6/2015,H,W022,91004118.0,7560051
2,2015-01-01,-8.0,-8.0,4501565923,71.0,102,8.0,1/19/2015,H,W022,91006186.0,0066009
3,2015-01-01,798.4,798.4,4501561724,1.0,101,798.4,1/7/2015,S,W022,91004599.0,7507124
4,2015-01-01,898.2,898.2,4501561724,1.0,101,898.2,1/7/2015,S,W022,91004599.0,7507124
...,...,...,...,...,...,...,...,...,...,...,...,...
371584,2020-11-01,0.0,-10000.0,4502776215,1.0,161,10000.0,11/16/2020,H,W022,92061972.0,7501801
371585,2020-11-01,50.0,50.0,4502776084,8.0,101,50.0,11/17/2020,S,W022,92068309.0,0063875
371586,2020-11-01,7922.0,7922.0,4502777993,1.0,101,7922.0,11/16/2020,S,W022,92055760.0,F00000384
371587,2020-11-01,1800.0,1800.0,4502777500,7.0,101,1800.0,11/16/2020,S,W022,92055938.0,0896481
371588,2020-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
d1501=pd.merge(df15_rep,df01_rep,how="left",on="Reporting Date")

In [57]:
df01p = df01.loc[(df01['PLANT'] == 'WND1') | (df01['PLANT'] == 'DE02')]

In [76]:
df01_rep.PLANT.unique()

array([nan, 'WND1', 'DE02'], dtype=object)

In [78]:
df01p_15=pd.merge(df01p,df15,how="outer",on=["Reporting Date","VENDOR","MATERIAL"])

In [98]:
df01p_15[(df01p_15['VENDOR'] == 92054591) & (df01p_15['Reporting Date'] == '2020-01-01')]

,Reporting Date,Outgoing,DOC_NUM_x,DOC_ITEM_x,PROCESSKEY,DOC_DATE,DOC_CAT,PURCH_ORG,VENDOR,BWAPPLNM,...,Incoming,New GR QTY,DOC_NUM_y,DOC_ITEM_y,MOVE_TYPE,GR_QTY,PLANT_y,PSTNG_DATE,DCINDIC,/BIC/PURCH_ORG
70715,2020-01-01,1030.0,4502610039,1.0,7.0,1/28/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70716,2020-01-01,1030.0,4502610039,1.0,7.0,1/28/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70717,2020-01-01,1030.0,4502610039,1.0,7.0,1/28/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70718,2020-01-01,1030.0,4502610039,1.0,7.0,1/28/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70719,2020-01-01,2240.0,4502611035,1.0,7.0,1/29/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70720,2020-01-01,2240.0,4502611035,1.0,7.0,1/29/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70721,2020-01-01,2240.0,4502611035,1.0,7.0,1/29/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70722,2020-01-01,2240.0,4502611035,1.0,7.0,1/29/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70723,2020-01-01,800.0,4502610039,1.0,6.0,1/28/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70724,2020-01-01,800.0,4502610039,1.0,6.0,1/28/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70725,2020-01-01,800.0,4502610039,1.0,6.0,1/28/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70726,2020-01-01,800.0,4502610039,1.0,6.0,1/28/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70727,2020-01-01,1780.0,4502611035,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70728,2020-01-01,1780.0,4502611035,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70729,2020-01-01,1780.0,4502611035,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70730,2020-01-01,1780.0,4502611035,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70731,2020-01-01,7300.0,4502611035,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70732,2020-01-01,7300.0,4502611035,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70733,2020-01-01,7300.0,4502611035,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70734,2020-01-01,7300.0,4502611035,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70735,2020-01-01,2240.0,4502611035,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70736,2020-01-01,2240.0,4502611035,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70737,2020-01-01,2240.0,4502611035,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70738,2020-01-01,2240.0,4502611035,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70739,2020-01-01,1780.0,4502611697,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70740,2020-01-01,1780.0,4502611697,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70741,2020-01-01,1780.0,4502611697,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70742,2020-01-01,1780.0,4502611697,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70743,2020-01-01,7300.0,4502611700,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70744,2020-01-01,7300.0,4502611700,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70745,2020-01-01,7300.0,4502611700,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70746,2020-01-01,7300.0,4502611700,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70747,2020-01-01,2240.0,4502611035,1.0,6.0,1/29/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70748,2020-01-01,2240.0,4502611035,1.0,6.0,1/29/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70749,2020-01-01,2240.0,4502611035,1.0,6.0,1/29/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70750,2020-01-01,2240.0,4502611035,1.0,6.0,1/29/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
70751,2020-01-01,1030.0,4502610039,1.0,5.0,1/28/2020,F,W022,92054591,MM,...,22330.0,22330.0,X502506135,2.0,101,22330.0,DE02,1/23/2020,S,W022
70752,2020-01-01,1030.0,4502610039,1.0,5.0,1/28/2020,F,W022,92054591,MM,...,75620.0,75620.0,X502506135,2.0,101,75620.0,DE02,1/23/2020,S,W022
70753,2020-01-01,1030.0,4502610039,1.0,5.0,1/28/2020,F,W022,92054591,MM,...,73380.0,73380.0,X502482203,2.0,101,73380.0,DE02,1/22/2020,S,W022
70754,2020-01-01,1030.0,4502610039,1.0,5.0,1/28/2020,F,W022,92054591,MM,...,28680.0,28680.0,X502482203,2.0,101,28680.0,DE02,1/23/2020,S,W022
109875,2020-01-01,4740.0,4502611009,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,76810.0,76810.0,X502482204,1.0,101,76810.0,DE02,1/14/2020,S,W022
109876,2020-01-01,4740.0,4502611009,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,72650.0,72650.0,X502506137,1.0,101,72650.0,DE02,1/28/2020,S,W022
109877,2020-01-01,4740.0,4502611009,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,3890.0,3890.0,4502600318,1.0,101,3890.0,DE02,1/30/2020,S,W022
109878,2020-01-01,4740.0,4502611009,3.0,5.0,1/29/2020,F,W022,92054591,MM,...,29950.0,29950.0,X502506136,1.0,101,29950.0,DE02,1/15/2020,S,W022
109879,2020-01-01,5310.0,4502611009,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,76810.0,76810.0,X502482204,1.0,101,76810.0,DE02,1/14/2020,S,W022
109880,2020-01-01,5310.0,4502611009,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,72650.0,72650.0,X502506137,1.0,101,72650.0,DE02,1/28/2020,S,W022
109881,2020-01-01,5310.0,4502611009,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,3890.0,3890.0,4502600318,1.0,101,3890.0,DE02,1/30/2020,S,W022
109882,2020-01-01,5310.0,4502611009,1.0,5.0,1/29/2020,F,W022,92054591,MM,...,29950.0,29950.0,X502506136,1.0,101,29950.0,DE02,1/15/2020,S,W022
109883,2020-01-01,4780.0,4502611009,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,76810.0,76810.0,X502482204,1.0,101,76810.0,DE02,1/14/2020,S,W022
109884,2020-01-01,4780.0,4502611009,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,72650.0,72650.0,X502506137,1.0,101,72650.0,DE02,1/28/2020,S,W022
109885,2020-01-01,4780.0,4502611009,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,3890.0,3890.0,4502600318,1.0,101,3890.0,DE02,1/30/2020,S,W022
109886,2020-01-01,4780.0,4502611009,2.0,5.0,1/29/2020,F,W022,92054591,MM,...,29950.0,29950.0,X502506136,1.0,101,29950.0,DE02,1/15/2020,S,W022
109887,2020-01-01,4780.0,4502611763,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,76810.0,76810.0,X502482204,1.0,101,76810.0,DE02,1/14/2020,S,W022
109888,2020-01-01,4780.0,4502611763,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,72650.0,72650.0,X502506137,1.0,101,72650.0,DE02,1/28/2020,S,W022
109889,2020-01-01,4780.0,4502611763,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,3890.0,3890.0,4502600318,1.0,101,3890.0,DE02,1/30/2020,S,W022
109890,2020-01-01,4780.0,4502611763,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,29950.0,29950.0,X502506136,1.0,101,29950.0,DE02,1/15/2020,S,W022
109891,2020-01-01,4740.0,4502611777,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,76810.0,76810.0,X502482204,1.0,101,76810.0,DE02,1/14/2020,S,W022
109892,2020-01-01,4740.0,4502611777,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,72650.0,72650.0,X502506137,1.0,101,72650.0,DE02,1/28/2020,S,W022
109893,2020-01-01,4740.0,4502611777,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,3890.0,3890.0,4502600318,1.0,101,3890.0,DE02,1/30/2020,S,W022
109894,2020-01-01,4740.0,4502611777,1.0,5.0,1/30/2020,F,W022,92054591,MM,...,29950.0,29950.0,X502506136,1.0,101,29950.0,DE02,1/15/2020,S,W022

In [99]:
df01p_15.to_csv("final_unionandouterCR.csv",index=False)